//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityID { get; set; }
        public string ActivityName { get; set; }
        public int ProductInfoID { get; set; }
        public System.DateTime ActivityStartDate { get; set; }
        public System.DateTime ActivityDueDate { get; set; }
        public string Partner { get; set; }
        public string ActivityContext { get; set; }
    
        public virtual ProductInfo ProductInfo { get; set; }
    }
}
